version: '3.9'
services: 
  client:
    build: client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/usr/app
      - /usr/app/build
      - /usr/app/node_modules
  user-service:
    build: user-service
    ports:
      - "6001:6001"
    volumes:
      - ./user-service:/usr/app
      - /usr/app/node_modules
  tournament-service:
    build: tournament-service
    ports:
      - "6002:6002"
    volumes:
      - ./tournament-service:/usr/app
      - /usr/app/node_modules
  notification-service:
    build: notification-service
    ports:
      - "6003:6003"
    volumes:
      - ./notification-service:/usr/app
      - /usr/app/node_modules
  event-bus:
    build: event-bus
    volumes:
      - ./event-bus:/usr/app
      - /usr/app/node_modules